AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an EC2 instance

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small
    Description: EC2 instance type

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Existing EC2 KeyPair for SSH access

  AmiId:
    Type: AWS::EC2::Image::Id
    Description: AMI ID (Amazon Linux, Ubuntu, etc.)

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: My-timo7-EC2-Instance

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance

  PublicIP:
    Description: Public IP address
    Value: !GetAtt EC2Instance.PublicIp
